# Generated by Django 4.0.2 on 2022-04-03 10:36

from django.db import migrations


PARAMETERS_DATA = [
    {
        'name': 'min_temp'
    },
    {
        'name': 'max_temp'
    },
    {
        'name': 'mean_temp'
    },
    {
        'name': 'rainfall'
    }
]

REGION_DATA = [
    {
        'name': 'UK'
    }
]

PARAMETER_REGION_DATA = [
    {
        'parameter': 'min_temp',
        'region': 'UK',
        'url': 'https://www.metoffice.gov.uk/pub/data/weather/uk/climate/datasets/Tmin/date/UK.txt'
    },
    {
        'parameter': 'max_temp',
        'region': 'UK',
        'url': 'https://www.metoffice.gov.uk/pub/data/weather/uk/climate/datasets/Tmax/date/UK.txt'
    },
    {
        'parameter': 'mean_temp',
        'region': 'UK',
        'url': 'https://www.metoffice.gov.uk/pub/data/weather/uk/climate/datasets/Tmean/date/UK.txt',
    },
    {
        'parameter': 'rainfall',
        'region': 'UK',
        'url': 'https://www.metoffice.gov.uk/pub/data/weather/uk/climate/datasets/Rainfall/date/UK.txt'
    }
]


def migrate_to_parameter_model(apps, schema_editor):
    Parameter = apps.get_model('farmsetu', 'Parameter')
    Region = apps.get_model('farmsetu', 'Region')
    ParameterRegion = apps.get_model('farmsetu', 'ParameterRegion')

    insert_data = []
    for parameter in PARAMETERS_DATA:
        insert_data.append(
            Parameter(
                name=parameter['name']
            )
        )

    Parameter.objects.bulk_create(insert_data)

    insert_data = []
    for region in REGION_DATA:
        insert_data.append(
            Region(
                name=region['name']
            )
        )

    Region.objects.bulk_create(insert_data)

    insert_data = []
    for parameter_region in PARAMETER_REGION_DATA:
        insert_data.append(
            ParameterRegion(
                parameter=Parameter.objects.get(name=parameter_region['parameter']),
                region=Region.objects.get(name=parameter_region['region']),
                url=parameter_region['url']
            )
        )

    ParameterRegion.objects.bulk_create(insert_data)


class Migration(migrations.Migration):

    dependencies = [
        ('farmsetu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_to_parameter_model)
    ]
