# Generated by Django 4.2.3 on 2023-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsetu', '0001_insert_parameter_region_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='parameterregion',
            unique_together={('parameter', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('year', 'parameter', 'region')},
        ),
    ]
